### ISSUE TITLE
Argon2 id mode?

### ISSUE THREAD

**Issue by azhang66** [ranisalt/node-argon2-cli#23]
### Steps to reproduce
1. Attempt to run `argon2-cli` to hash a password using argon2's id mode.
2. See that this is not documented to be possible.

### Expected behavior
`argon2-cli` should be able to hash a password using argon2's id mode.

### Actual behaviour
`argon2-cli` is unable to do so.

### Environment
**Operating system:** macOS High Sierra 10.13.4

**Node version:** v8.11.2

**Compiler version:** Apple LLVM version 9.1.0 (clang-902.0.39.1)

**Comment by ranisalt** [comment]
This CLI tool is highly outdated currently, mostly because JS lacks a decent argument parser without a shitload of dependencies. I could try to update it for your use case though.

**Comment by azhang66** [comment]
That's works perfectly! Thanks!
